# Generated by Django 3.1.5 on 2021-07-15 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='store_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.storetype'),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='medicine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicinetype'),
        ),
        migrations.AlterField(
            model_name='medicinedetails',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicalstore'),
        ),
    ]
