# Generated by Django 3.1.5 on 2021-07-16 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210716_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.medicalstore'),
        ),
    ]
