# Generated by Django 3.1.5 on 2021-07-16 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210716_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalstore',
            name='store_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.storetype'),
        ),
    ]
