# Generated by Django 3.1.5 on 2021-07-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210716_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinedetails',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.medicalstore'),
        ),
    ]
